//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextMaid.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextMaid.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   🔍Check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckButton {
            get {
                return ResourceManager.GetString("CheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   🧼Clean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CleanButton {
            get {
                return ResourceManager.GetString("CleanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text copied! Ready to serve wherever you need it~ 📋과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClipboardCopied {
            get {
                return ResourceManager.GetString("ClipboardCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eep! I had trouble copying... Here&apos;s the problem 😢과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClipboardError {
            get {
                return ResourceManager.GetString("ClipboardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   🚫Emoji Clean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EmojiCleanButton {
            get {
                return ResourceManager.GetString("EmojiCleanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emojis and hidden spaces? Gone! Leave it to your trusty maid~ 💖과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EmojiCleaned {
            get {
                return ResourceManager.GetString("EmojiCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelResult {
            get {
                return ResourceManager.GetString("LabelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LabelTextInput {
            get {
                return ResourceManager.GetString("LabelTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   💾Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I’ve cleaned up all the hidden spaces, Master! 🧹과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnicodeCleaned {
            get {
                return ResourceManager.GetString("UnicodeCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oh no Master, I found some sneaky hidden spaces! 💦과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnicodeDetected {
            get {
                return ResourceManager.GetString("UnicodeDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All clean~ No hidden spaces here! ✨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnicodeNotDetected {
            get {
                return ResourceManager.GetString("UnicodeNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextMaid - Your Text Cleaner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
